wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.4
    framework: fastai
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1710089819.0
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 4
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.10.13
      5: 0.16.4
      8:
      - 2
      - 5
      13: linux-x86_64
epochs:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.0005
